name: Kodi Addon-Checker

on: [pull_request]

jobs:
  kodi-addon-checker:
    runs-on: ubuntu-latest
    name: Kodi Addon-Checker
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install --user kodi-addon-checker
        
    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done

    - name: Extract job variables
      shell: bash

      run: |
        git --no-pager diff --name-only HEAD^
        echo "addon=$(git --no-pager diff --name-only ..origin/${{ github.event.pull_request.base.ref }} | grep / | cut -d / -f1 | sort | uniq)" >> $GITHUB_OUTPUT
      id: extract_vars

    - name: Addon-Check
      run: $HOME/.local/bin/kodi-addon-checker --branch=${{ github.event.pull_request.base.ref }} --PR ${{ steps.extract_vars.outputs.addon }}
